include:
    -   project: ci-cd/templates
        file: 'php/php.yaml'

default:
    image: registry.gitlab.cdn77.eu/library/functions/build

Build Image:
    extends: .build-image

Infection:
    extends: .job
    script: make infection

Static Analysis (Psalm):
    extends: .job
    script: make psalm
