name: "Static Analysis"

on:
  pull_request:
  push:
    branches:
      - "*.*.x"
  workflow_dispatch:

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"
          extensions: "ds, mbstring"
          tools: "cs2pr"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "vendor/bin/phpstan --error-format=checkstyle | cs2pr"

  static-analysis-composer-unused:
    name: "Static Analysis with Composer Unused"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"
          extensions: "ds, mbstring"
          tools: "cs2pr"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Run Composer Unused"
        run: "vendor/bin/composer-unused"
